default_context:
    profile_name: "threadripper"
    cores: 48
    resources: "parallel_downloads: 3, mem_gb: 64"
    conda: "True"
    singularity: "False"
    keep_going: "True"
    config: "ascp_path: $HOME/.aspera/connect/bin/ascp, ascp_key: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh"
