default_context:
    profile_name: "moldev"
    max_jobs: 250
    default_rule: "partition: ocimumpartition, time: 60, mem_gb: 2"
    optional_rules: "bowtie2_align(partition: ocimumpasserpartition), bwa_mem(partition: ocimumpasserpartition), hisat2_align(partition: ocimumpasserpartition), star_align(partition: ocimumpasserpartition)"
    resources: "parallel_downloads: 3, mem_gb: 999"
    conda: "True"
    singularity: "False"
    keep_going: "True"
    config: "ascp_path: $HOME/.aspera/connect/bin/ascp, ascp_key: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh"
