default_context:
    profile_name: "moldev"
    max_jobs: 250
    default_rule: "partition: ocimumpasserpartition, time: 60, mem_gb: 2"
    optional_rules: "id2sra(partition: ocimumpartition)"
    resources: "parallel_downloads: 3"
    conda: "True"
    singularity: "False"
    keep_going: "True"
    config: "ascp_path: $HOME/.aspera/connect/bin/ascp, ascp_key: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh"
