# execution
cores: 48
keep-going: True
resources:
  - parallel_downloads=1
  - mem_gb=63
config: 
  - ncbi_key=ba36a74749126e0d9558b7e19967417c3407
  - ncbi_requests=10


# environment
use-conda: True
use-singularity: True
