# execution
nodes: {{cookiecutter.max_jobs}}
cores: {{cookiecutter.max_jobs}}
{% if cookiecutter.resources|length -%}
resources:
{%- for keyval in cookiecutter.resources.replace(' ', '').split(',') -%}
{% set key, value = keyval.replace(':', '=').split('=') %}
  - {{key}}={{value}}
{%- endfor %}
{%- endif %}
{% if cookiecutter.config|length -%}
config:
  - email={{cookiecutter.email}}
{%- for keyval in cookiecutter.config.replace(' ', '').split(',') -%}
{% set key, value = keyval.replace(':', '=').split('=') %}
  - {{key}}={{value}}
{%- endfor %}
{%- endif %}
keepgoing: {{cookiecutter.keepgoing}}
force_incomplete: {{cookiecutter.force_incomplete}}

# environment
use_conda: True

# behaviour
latency_wait: 15

# cluster
jobname: seq2science-{jobid}-{rule}
cluster_config: ~/.config/snakemake/{{cookiecutter.profile_name}}/cluster.yaml
cluster_status: ~/.config/snakemake/{{cookiecutter.profile_name}}/status.py
cluster: ~/.config/snakemake/{{cookiecutter.profile_name}}/scheduler.py
